In [1]:
def maximun (a,b,c):
    list = [a,b,c]
    return max(list)

a = int(input("Enter a: "))
b = int( input("Enter b: "))
c = int( input("Enter c: "))

print(maximun(a,b,c))

Enter a: 10
Enter b: 20
Enter c: 30
30


In [1]:
n = int(input("enter n "))

for i in range(1,11):
    print(i*n)

10
20
30
40
50
60
70
80
90
100


In [13]:
# replace a word in a string

def replace_word(string,word,newWord):
    return string.replace(word,newWord)

string = "ASDFGHJKL"
word = "ASD"
newWord = "QWERTY"

print(replace_word(string,word,newWord))


QWERTYFGHJKL


In [14]:
# replace the first word in a string

def replace_word(string,word,newWord):
    return string.replace(word,newWord,1)

string = "AAAAAAAAAAAAAAB"
word = "A"
newWord = "a"

print(replace_word(string,word,newWord))


aAAAAAAAAAAAAAB


In [17]:
# combination of three digits

list = [1,2,3]

for i in list:
    for j in list:
        for k in list:
            if i != j and j != k and i != k:
                print(i,j,k)

1 2 3
1 3 2
2 1 3
2 3 1
3 1 2
3 2 1


In [ ]:
# simple email validation

def emailValidation(email):
    if "@" in email and "." in email:
        return True
    else:
        return False

In [21]:
# advanced email validation

import re

def emailValidation(email):
    if re.search(r"[@.]",email):
        return True
    else:
        return False
    
regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b'
def emailValidationAdvaced(email):
    if re.search(regex,email):
        return True
    else:
        return False
    
email = input("Enter email: ")
print(emailValidation(email))
print(emailValidationAdvaced(email))


True
True


In [ ]:
# regex for valid password in python

# 1. at least 1 letter between [a-z]
# 2. at least 1 number between [0-9]
# 3. at least 1 letter between [A-Z]
# 4. at least 1 character from [$#@]
# 5. minimum length 6 characters
# 6. maximum length 16 characters

import re

regex = r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$#@])[A-Za-z\d$#@]{6,16}$'

def passwordCheck(password):
    if re.search(regex,password
,):
        return True
    else:
        return False

In [ ]:
# try and except

try:
    a = int(input("Enter a: "))
    b = int(input("Enter b: "))
    print(a/b)
except:
    print()


In [24]:
from email_validator import validate_email, EmailNotValidError

def emailValidation(email):
    try:
        valid = validate_email(email)
        email = valid.email
        return True
    except EmailNotValidError as e:
        print(e)
        return False
    
email = input("Enter email: ")

ModuleNotFoundError: No module named 'email_validator'

In [26]:
!pip install email_validator

#this is how we install a package

In [27]:
!pip install numpy

# use this instead of hard coding the algorithms

In [29]:
import numpy as np

Matrix1 = np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])

Matrix2 = np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])

result = np.array([[0,0,0],
          [0,0,0],
          [0,0,0]])

# use numpy to do matrix multiplication

result = np.dot(Matrix1,Matrix2)
print(result)





[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [31]:
x = [[1,2,3],
           [4,5,6],
           [7,8,9]]

y = [[1,2,3],
           [4,5,6],
           [7,8,9]]

result = [[0,0,0],
            [0,0,0],
            [0,0,0]]


# iterate through rows
for i in range(len(x)):
    # iterate through columns
    for j in range(len(x[0])):
         result[i][j] = x[i][j] + y[i][j]


print(result)

# for r in result:
#     print(r)



[[2, 4, 6], [8, 10, 12], [14, 16, 18]]
